version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"  # Откройте порт 8080 для доступа к вашему приложению
    depends_on:
      - db  # Убедитесь, что база данных запускается перед вашим приложением

  db:
    image: mysql:8.0
    environment:
     - MYSQL_ROOT_PASSWORD
     - MYSQL_DATABASE
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
#    restart: always
#    env_file:
#      - .env
    ports:
      - "3307:3306"  # Откройте порт 3306 для доступа к MySQL






#docker-compose config  to check
#docker-compose up --build   to build and run